# Site
name: "TJ Sokol Velké Přílepy"
title: "TJ Sokol Velké Přílepy"
description: "Fotbalový klub, který hraje fotbalové soutěže jak v kategorii mužů, tak žáků."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: /velke-prilepy
google_analytics: ''
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Týna:
    name: Kristýna
    display_name: Týna
    gravatar: https://cs.gravatar.com/userimage/233273694/cb03d1dfea71a5143353d0c9e0b1a964.png
    email: tynkagottwaldova@gmail.com
    web: https://www.wowthemes.net
    description: "Auktorka webu, TJ Sokol Velké Přílepy, která se zabývá hráči v mužském družstvu."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - kategorie
  layout: archive
  permalinks:
    category: '/kategorie/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
